### ISSUE TITLE
Docker build broken

### ISSUE THREAD

**Issue by lewismc** [RDFLib/pyLODE#102]
```
docker --version
Docker version 19.03.12, build 48a66213fe
```

```
docker build -t pylode:latest --build-arg PYTHON_VERSION=3.8-slim .
Sending build context to Docker daemon  84.17MB
Step 1/13 : ARG PYTHON_VERSION=3.8-slim
Step 2/13 : FROM python:$PYTHON_VERSION
 ---> 9d84edf35a0a
Step 3/13 : MAINTAINER pyLODE Developers <https://github.com/RDFLib/pyLODE/graphs/contributors>
 ---> Using cache
 ---> db3372bd2f11
Step 4/13 : USER root
 ---> Using cache
 ---> 2842c31fff8b
Step 5/13 : RUN apt-get update && 	apt-get upgrade -y --allow-downgrades --allow-remove-essential --allow-change-held-packages
 ---> Using cache
 ---> b1fcfe393ede
Step 6/13 : COPY requirements.server.txt /tmp/
 ---> 4604cdab147e
Step 7/13 : RUN pip install -r /tmp/requirements.server.txt
 ---> Running in 62dcbb4e0d15
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.9.1-py3-none-any.whl (115 kB)
Collecting falcon
  Downloading falcon-2.0.0-py2.py3-none-any.whl (163 kB)
Collecting gunicorn
  Downloading gunicorn-20.0.4-py2.py3-none-any.whl (77 kB)
Collecting soupsieve>1.2
  Downloading soupsieve-2.0.1-py3-none-any.whl (32 kB)
Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.8/site-packages (from gunicorn->-r /tmp/requirements.server.txt (line 3)) (47.1.1)
Installing collected packages: soupsieve, beautifulsoup4, falcon, gunicorn
Successfully installed beautifulsoup4-4.9.1 falcon-2.0.0 gunicorn-20.0.4 soupsieve-2.0.1
WARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Removing intermediate container 62dcbb4e0d15
 ---> 97b5a5d4c508
Step 8/13 : ADD . /app
 ---> 2b86ea947c22
Step 9/13 : WORKDIR /app
 ---> Running in b0881ed02b82
Removing intermediate container b0881ed02b82
 ---> 993c7fd59105
Step 10/13 : RUN python3 setup.py install
 ---> Running in 6c75dc5645c2
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from pylode.common import VERSION
  File "/app/pylode/__init__.py", line 1, in <module>
    from rdflib.plugin import register, Serializer
ModuleNotFoundError: No module named 'rdflib'
The command '/bin/sh -c python3 setup.py install' returned a non-zero code: 1
```

... working on fix now

**Comment by nicholascar** [comment]
I'm using Docker extensively at SURROUND (wasn't before) so I'll get back to this task shortly
